### PR TITLE
:bug: fix for matplotlib > 3.6.2

### PR DESCRIPTION
**Pull request by quirinziessler**
this PR fixes Issue #21

### CODE REVIEW

**Comment by veghp** [comment]
Thank you -- a solution has already been posted in https://github.com/Edinburgh-Genome-Foundry/pdf_reports/pull/20/files and will look into releasing it soon.

**Comment by quirinziessler** [comment]
👍 Sorry, I missed the fix in the other PR. Feel free to close this one and use the other solution if it works better. Looking forward to see this closed soon!

**Comment by quirinziessler** [comment]
Hi @veghp - any updates on this topic? Would appreciate a fix for this.

**Comment by veghp** [comment]
Released: https://github.com/Edinburgh-Genome-Foundry/pdf_reports/releases/tag/v0.3.5

https://pypi.org/project/pdf-reports/0.3.5/

**Comment by quirinziessler** [comment]
Thanks a lot!

**Pull request closed without merging**
